name: Build and Package Application

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Build application using PHP Docker image
      run: |
        docker run --rm -v "${{ github.workspace }}:/app" -w /app php:8.3-cli-alpine sh -c "
          apk add --no-cache curl \
          && curl -sS https://getcomposer.org/download/2.7.6/composer.phar -o composer.phar \
          && php composer.phar config --global --no-ansi --no-interaction \
          && php composer.phar install --optimize-autoloader --no-dev --no-interaction
        "

    - name: Create tar.gz package
      run: |
        tar -czvf application.tar.gz .

    - name: Push to build repository
      env:
        REPO_URL: https://github.com/your-username/build-repo.git
        TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git config --global javeriakhn "GitHub Actions"
        git config --global javeriakashan97@gmail.com "actions@github.com"
        git clone https://$TOKEN@github.com/your-username/build-repo.git build-repo
        mv application.tar.gz build-repo/
        cd build-repo
        git add application.tar.gz
        git commit -m "Add build for tag ${{ github.ref }}"
        git push origin main
